logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  # 이메일
  mail:
    host: smtp.gmail.com
    port: 587
    username: seongyun8063@gmail.com # 앱 비밀번호 발급받은 google 계정
    password: rlaqjfsgajpgafvb # 발급받은 앱 비밀번호 (16자리 입니다.) -> 복붙
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 
            
            
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao

        provider:
          kakao:
            
            
            
            user-name-attribute: {}
jwt:
  secretKey: 
  access:
    expiration: 1800000 # 30분
    header: Authorization

  refresh:
    expiration: 2419200000 # 4주
    header: refreshToken
server:
  port: 1000


