logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
***REMOVED***     
    username: {username}
    password: {password}


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 
            
            redirect-uri: https://localhost:4000/api/users/oauth2/login
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao

        provider:
          kakao:
            
            
            
            user-name-attribute: {}
jwt:
  secretKey: 
  access:
    expiration: 1800000 # 30분
    header: Authorization

  refresh:
    expiration: 2419200000 # 4주
server:
  port: 1000